package com.grace.quant.entity;

import java.util.Date;
import lombok.Data;

@Data
public class Cash {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.id
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.account_id
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.market_value
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Float marketValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.nav
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Float nav;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.pnl
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Float pnl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.fpnl
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Float fpnl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.frozen
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Float frozen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.available
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Float available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.balance
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Float balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.order_frozen
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Float orderFrozen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.created_at
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.updated_at
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.recv_at
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    private Date recvAt;
    /**
     * use lombok to replace the following code about get/set
     */

//
//    public Integer getId() {
//        return id;
//    }
//
//    public void setId(Integer id) {
//        this.id = id;
//    }
//
//    public String getAccountId() {
//        return accountId;
//    }
//
//    public void setAccountId(String accountId) {
//        this.accountId = accountId;
//    }
//
//    public Float getMarketValue() {
//        return marketValue;
//    }
//
//    public void setMarketValue(Float marketValue) {
//        this.marketValue = marketValue;
//    }
//
//    public Float getNav() {
//        return nav;
//    }
//
//    public void setNav(Float nav) {
//        this.nav = nav;
//    }
//
//    public Float getPnl() {
//        return pnl;
//    }
//
//    public void setPnl(Float pnl) {
//        this.pnl = pnl;
//    }
//
//    public Float getFpnl() {
//        return fpnl;
//    }
//
//    public void setFpnl(Float fpnl) {
//        this.fpnl = fpnl;
//    }
//
//    public Float getFrozen() {
//        return frozen;
//    }
//
//    public void setFrozen(Float frozen) {
//        this.frozen = frozen;
//    }
//
//    public Float getAvailable() {
//        return available;
//    }
//
//    public void setAvailable(Float available) {
//        this.available = available;
//    }
//
//    public Float getBalance() {
//        return balance;
//    }
//
//    public void setBalance(Float balance) {
//        this.balance = balance;
//    }
//
//    public Float getOrderFrozen() {
//        return orderFrozen;
//    }
//
//    public void setOrderFrozen(Float orderFrozen) {
//        this.orderFrozen = orderFrozen;
//    }
//
//    public Date getCreatedAt() {
//        return createdAt;
//    }
//
//    public void setCreatedAt(Date createdAt) {
//        this.createdAt = createdAt;
//    }
//
//    public Date getUpdatedAt() {
//        return updatedAt;
//    }
//
//    public void setUpdatedAt(Date updatedAt) {
//        this.updatedAt = updatedAt;
//    }
//
//    public Date getRecvAt() {
//        return recvAt;
//    }
//
//    public void setRecvAt(Date recvAt) {
//        this.recvAt = recvAt;
//    }

}