package com.grace.quant.entity;

import java.util.Date;
import lombok.Data;

@Data
public class Position {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.id
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.account_id
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.symbol
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.side
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Integer side;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.volume
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Integer volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.volume_today
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Integer volumeToday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.vwap
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Float vwap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.vwap_diluted
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Float vwapDiluted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.market_value
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Float marketValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.price
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.fpnl
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Float fpnl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.cost
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Float cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.available_now
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Integer availableNow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.created_at
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.updated_at
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.recv_at
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    private Date recvAt;

}