package com.grace.quant.repository;

import com.grace.quant.entity.Cash;

public interface CashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    int insert(Cash row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    int insertSelective(Cash row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    Cash selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    int updateByPrimaryKeySelective(Cash row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash
     *
     * @mbg.generated Wed Jan 10 11:54:27 CST 2024
     */
    int updateByPrimaryKey(Cash row);
}