package com.grace.quant.repository;

import com.grace.quant.entity.Cash;
import com.grace.quant.entity.Position;

import java.util.List;

public interface PositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    int insert(Position row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    int insertSelective(Position row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    Position selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    int updateByPrimaryKeySelective(Position row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Thu Jan 11 17:17:56 CST 2024
     */
    int updateByPrimaryKey(Position row);

    List<Position> findAll();
}